set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports sysclk]  
create_clock -period 10.00 [get_ports sysclk]  
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN V17 [get_ports {closed_sw}]
	set_property IOSTANDARD LVCMOS33 [get_ports {closed_sw}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports btn_X0]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports btn_X1] 
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports btn_reset]  
